src/clients.js, src/company.js, src/components/forms/CreateEntityLayout.js, src/components/forms/EditEntityLayout.js, src/contracts.js, src/employees.js
Fixed errors in company, clients and contracts (creating editing and list).
Reorder employees fields in create and edit
=> fixed errors in company, clients, contracts and employee

src/employees.js
Adding the feature to show employees as cards. Note: image is hardcoded until we have the feature to upload images.
=> EN-9-CARDS: Adding cards for employees

src/components/forms/CreateEmployeeLayout.js, src/components/forms/EditEmployeeLayout.js, src/components/forms/ReferenceSelectArrayInputItem.js, src/employees.js
added new inputs for the new employee fields and create layouts for create and edit employee
=> EN-31 New fields in Employee Personal Information

.github/pull_request_template.md, .github/workflows/deploy-dev-aws.yml, .github/workflows/deploy-prod-aws.yml
Add ci cd config to deploy into prod
https://entropyteam.atlassian.net/browse/EN-25
=> EN-25: add production deploy

src/App.js, src/assignments.js
=> En 6 - Add entity assignment

src/contracts.js
=> ADMIN-UI-4-ADDITIONS New fields for contract

src/App.js, src/employees.js
Hide tabs in employee profile, change employee avatar and dashboard commented
https://entropyteam.atlassian.net/browse/EN-35
New landing page when users log in with new employees profile image
Empty tabs hide until developed
=> EN-35 Hide/Update fields for prod

src/employees.js
New fields were added in the employee profile
https://entropyteam.atlassian.net/browse/EN-38
=> EN-38 Displayed new field in Employee profile

src/components/layout/CustomMenu.js
=> EN-43: add menu icons

src/assignments.js, src/contracts.js, src/employees.js
Fix full name and remove internal id from employee card
=> Fix full name and remove internal id form employee card

Dockerfile, src/employees.js
Display active and inactive contracts in employee profile. Contract table has new column called status where the latest contract is diffferentiated
https://entropyteam.atlassian.net/browse/EN-44
Contracts in employee profile
=> EN-44 Displayed Active and Inactive contracts in Employee profile

src/assignments.js, src/contracts.js, src/employees.js
Label hours per week changes to hours per month in contract and assignment
https://entropyteam.atlassian.net/browse/EN-47
In contracts
In assignments
=> En 47 change label hours per week to hours per month

public/index.html, src/App.js, src/Dashboard.js
Title of tab changes to Entroteam from Entropay
https://entropyteam.atlassian.net/browse/EN-51
New tab title
=> EN-51 title change to Entroteam

Dockerfile, src/contracts.js, src/employees.js
New column status in contract layout
https://entropyteam.atlassian.net/browse/EN-44
Column status in contract list
=> EN-44: Add column status in contract layout

src/clients.js
New fields add in clients forms: contact full name and contact email
https://entropyteam.atlassian.net/browse/EN-37
=> EN-37: Contact field in Client

src/company.js
Bug fix in company file, the edit form display all the information
https://entropyteam.atlassian.net/browse/EN-56
Companies list
Edit form displayed
Changes confirmed
=> EN-56: Companies cannot be edited bug fix

src/assignments.js, src/clients.js, src/company.js, src/components/forms/FormSections.jsx, src/components/forms/PaymentSection.jsx, src/contracts.js, src/employees.js, src/projects.js
The contract form has the flexibility to add more than one salary in payment settlement section.
https://entropyteam.atlassian.net/browse/EN-52
Payment Settlement Section
=> EN-52: Update Salary and Contact type fields

src/App.js, src/employees.js, src/technologies.js
Add new input in employee form and field in employee profile.
https://entropyteam.atlassian.net/browse/EN-55
New input in employee form
Employee profile
Technology submenu in settings, only can be watched by admin and development role
Technology form
=> EN-55: Add technology field in employee

src/contracts.js, src/employees.js
In employee profile, order contracts and assignments by startDate.
https://entropyteam.atlassian.net/browse/EN-40
Manual testing
=> EN-40: order contracts and assignments by startDate

src/employees.js
Add pagination to employee list
Manual testing
=> Add employee pagination

src/employees.js
New search bar in employee list
https://entropyteam.atlassian.net/browse/EN-61
=> EN-61: Search bar

src/components/forms/FormSections.jsx, src/employees.js
Labour email add to employee form
Technologies next to profile in form
https://entropyteam.atlassian.net/browse/EN-67
Manual testing
Employee form
=> EN-67: New employee field and technologies location

src/App.js, src/assignments.js, src/contracts.js, src/resources.js
Display full Name in Employee dropdown for contracts and assigments
https://entropyteam.atlassian.net/browse/EN-48
Manual testing
=> EN-48: Display full Name in Employee dropdown

src/components/forms/ReferenceInputItem.jsx
Retrieve more than 25 items per entity in Reference input item
https://entropyteam.atlassian.net/browse/EN-71
Manual testing
=> EN-71: not all the employees are listed in Assignments and Contracts

src/employees.js
Now internal id is displayed in employee profile
https://entropyteam.atlassian.net/browse/EN-70
=> EN-70: Expose Internal ID in employee profile

.prettierignore, .prettierrc, src/components/buttons/RowRadioButtonGroup.jsx, src/employees.js, src/resources.js
Allow to toggle between card and list on Employee view
https://entropyteam.atlassian.net/browse/EN-68
- Added up to 6 users to test pagination
- Click on Employee sidebar and click radio button for card view and for list view
=> [EN-68] Employee view: Allow to toggle between card and list

src/employeeProfiles.js, src/employees.js, src/resources.js
- Add information + improve in employee cards
- Move employee profile to a new file
https://entropyteam.atlassian.net/browse/EN-62
Manual testing
=> EN-62: Employee UI card

src/components/fields/CustomizableChipField.jsx, src/contracts.js, src/employees.js, src/resources.js
- Created CustomizableChipField component to render custom content using a function passed as a child.
- Added HasPermission to control visibility of the content (Salary information)
https://entropyteam.atlassian.net/browse/EN-74
- Was created different types of _Payment settlement_ between the different currency types
-  Was created different types of _Payment settlement_ between the different modality types
- Was created different types of _Payment settlement_ up to three to test the component's arrange for the available space
=> [EN-74] Show salary in Contract view

src/employees.js
Route employee list click to employee profile
https://entropyteam.atlassian.net/browse/EN-62
Manual testing
=> EN-62: route employee list to profile

src/types/holidays.tsx
New improvement sort in holidays list, now holidays are sorted by date field in ASC criteria.
https://entropyteam.atlassian.net/browse/EN-78
Holidays List
=> EN-78-fix: new sort in holidays list by date

src/employeeProfiles.js
fix of a hook not being able to read undefined properties, putting validations on the if and  "?"
https://entropyteam.atlassian.net/browse/EN-
=> fix-assignments

src/employeeProfiles.js
Now we can see the summary of employee vacations correctly
https://entropyteam.atlassian.net/browse/EN-82
Vacation summary 
Vacation details
=> EN-82-Fix: Fix vacations summary 

src/seniorities.js
Add vacation days field to seniority
https://entropyteam.atlassian.net/browse/EN-105
Seniority list
Seniority form
=> EN-105: Vacation creation job

src/assignments.tsx, src/contracts.tsx
Add Search bar in Contracts and Assignments
https://entropyteam.atlassian.net/browse/EN-92
=> EN-92: Add Search bar in Contracts and Assignments

src/components/layout/CustomMenu.js, src/employeesReport.js, src/resources.js
The basic view for the employee report is finished
https://entropyteam.atlassian.net/browse/EN-109
=> EN-109: employee reporting

src/employeeProfiles.js
https://entropyteam.atlassian.net/browse/EN-115
=> EN115: Changed personalEmail for labourEmail

src/employeesReport.js, src/utils/exporter.js
The exporter function was modified to enable downloading the file in .xls format, and the employeesReport was adjusted to work with the exporter function.
https://entropyteam.atlassian.net/browse/EN-100
It was tested by downloading the excel and it is in the correct format
=> EN-100: Export to excel employee reporting

src/employeeProfiles.js
added vacations debit in personal information and changed StartDate and EndDate date format to dd/mm/yyyy
also changed assignment tab from "assigment" to "assignment"
https://entropyteam.atlassian.net/browse/EN-98
=> EN-98: added vacations debit in personal information and changed StartDate and EndDate date format to dd/mm/yyyy

src/employeeProfiles.js
removed vacations field from contract
https://entropyteam.atlassian.net/browse/EN-84
=> EN-84: removed vacations field from contract

src/ptos.tsx
Added the ability to take half a day off when creating a new PTO
https://entropyteam.atlassian.net/browse/EN-118
=> Added the abilty to take half a day off when requesting a PTO

src/employees.js, src/employeesReport.js, src/utils/exporter.js
Fixed reports being reported as an .xsl and not working correctly with excel. They are now being exported as a .csv
https://entropyteam.atlassian.net/browse/EN-120
=> EN-120: Fixed reports not being exported with the correct format

src/employeeProfiles.js
Now displaying the amount of time an employee has been working on the company on the employee's profile
https://entropyteam.atlassian.net/browse/EN-119
=> EN-119: Displaying amount of time working on the company

conf/conf.d/default.conf
Adding health check to nginx server
=> Set FE health check

src/employeesReport.js, src/utils/exporter.js
Added the ability to filter employees report and added a way to differentiate active from inactive employees on the report
https://entropyteam.atlassian.net/browse/EN-117
=> EN-117: Filter for employees report

src/components/buttons/BackButton.jsx, src/components/buttons/CancelButton.jsx, src/components/forms/CreateForm.jsx, src/components/forms/EditForm.jsx, src/components/layout/CustomActions.js
Fixed back button
Added cancel button when creating entities
https://entropyteam.atlassian.net/browse/EN-139
=> EN-139: Navigation improvements

src/employees.js
Make country a required field  for employee creation
https://entropyteam.atlassian.net/browse/EN-136
=> EN-136: Make country a required field  for employee creation

src/components/forms/EditForm.jsx, src/employeeProfiles.js, src/ptos.tsx
Deletio confirmation added. Also permissions were added to delete button, and all deletes buttons were removed from grids.
The confirmation title was changed to generic text.
https://entropyteam.atlassian.net/browse/EN-
=> EN-133 Delete confirmation

src/components/forms/ListBuilder.jsx, src/employeeProfiles.js, src/employees.js
Changes to accommodate to employee-country relationship
https://entropyteam.atlassian.net/browse/EN-136
=> EN-136: Pto calculation takes into account employees country

src/ptos.tsx, src/ptosReport.js, src/resources.js
Ptos report by employee and detail by employee ready
https://entropyteam.atlassian.net/browse/EN-145
https://entropyteam.atlassian.net/browse/EN-147
=> EN: Pto reporting

src/clientsPtosReport.js, src/employeesPtosReport.js, src/resources.js
Time off reporting total by client
Fixed bug with details not sending the year to fulter by year
https://entropyteam.atlassian.net/browse/EN-126
=> EN-126: Time off reporting total by client

src/clients.js
Added new field to client 
https://entropyteam.atlassian.net/browse/EN-158
=> EN-158: Added new field to client

src/clients.js, src/components/forms/FormSections.jsx
New field to client
https://entropyteam.atlassian.net/browse/EN-154
=> EN-154: added new field to client

src/employeeProfiles.js
Show details of expired vacations on empoyeesprofile
https://entropyteam.atlassian.net/browse/EN-151
=> EN-151: Expired vacations policy

src/clientsPtosReport.js, src/components/buttons/PtosReportsExportButton.jsx, src/employeesPtosReport.js
Created a custom button to export all details for ptos reports
https://entropyteam.atlassian.net/browse/EN-161
=> EN-161: Custom button to export ptos report

src/components/forms/MultiSelectInput.jsx
Roles were being limited to 25. Changed limits and sorted them out.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7301094882
Untested. Confident in the outcome.
=> EN-7301094882 Displayed new role added in Employee profile list

src/resources.js, src/salaryReport.js
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7575301701
=> creation of salaries report

package.json, src/App.js, yarn.lock
Migrating to react-admin v5.1.1
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7676173338
Tested basic functions locally.
=> Migrate to react admin 5

Dockerfile
Upgrade to node v20.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7724547301
This was tested locally.
=> Upgrade to node v20

yarn.lock
Removed yarn.lock locally and execute commands to re-create it.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7724547301
Tested locally using commands yarn start and yarn build, later one was producing the error when deploying. With these changes is working as expected locally.
=> Fix deployment of node v20

.gitignore, package.json, src/components/layout/CustomMenu.js
I decided to change the sidebar component from react suite for a component from MUI X because the styles from de original component doesn't change with the main theme application.
=> Fixing dark theme

src/contracts.tsx
https://entropyteam.atlassian.net/browse/EN-
=> remove the disabledCheck from employee field

src/assignments.tsx, src/components/forms/ReferenceInputItem.tsx, src/contracts.tsx, src/ptos.tsx
Solves this issues:
- https://3.basecamp.com/5776473/buckets/37034902/todos/7771487979
- https://3.basecamp.com/5776473/buckets/37034902/todos/7771490326
=> bugfixing and improvements

.github/workflows/deploy-dev-aws.yml
https://entropyteam.atlassian.net/browse/EN-
=> Update workflox to deploy to dev when merge pr to main

src/components/forms/ChildrenSection.jsx, src/components/forms/ChildrenSection.tsx, src/overtimes.tsx, src/resources.ts
Fix for dates being stored with a day of difference. Fixing issues with overtimes feature.
https://3.basecamp.com/5776473/buckets/37034902/todos/7834667982
https://3.basecamp.com/5776473/buckets/37034902/todos/7762561828
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7313297206
Tested locally.
=> Fixing bugs with dates and overtimes

src/App.tsx, src/components/layout/CustomMenu.tsx, src/overtimes.tsx
- When trying to retrieve resources in admin component we need to redirect to the login page. 
- Fix issue with search in overtimes.
- Fix warnings from react about keys.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/8046204784
Tested locally.
=> Fix issues with app not redirecting when token expires

src/billingReport.tsx, src/resources.ts
Add Billing Report with list view and export functionality
=> Add Billing Report with list view and export functionality

src/employeesReport.tsx
Fix dark mode in employee report
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/8075488213
=> Fix dark mode in employee report

src/employeeProfiles.tsx, src/overtimes.tsx
Increase overtime description length
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/8076400145
Tested locally.
=> Overtime description needs to be longer

.junie/guidelines.md, package.json, src/components/forms/FormSections.tsx, src/components/layout/CustomMenu.tsx, src/employeeFeedback.tsx, src/resources.ts, yarn.lock
This pull request introduces new functionality for managing employee feedback, updates dependencies, and provides development guidelines for the Entropay Admin UI. The most significant changes include the addition of employee feedback resources, integration of a rich text input component, and the creation of a comprehensive development guidelines document.
* **Employee Feedback Management**: Added new resources for managing employee feedback, including list, edit, and create views. These resources use a rich text input for detailed feedback and include predefined feedback source choices. (`src/employeeFeedback.tsx`, `src/resources.ts`) [[1]](diffhunk://#diff-c0aa7676caca313177782388eb3cac5a654a7ab7a39a52d9c6db9897c48caea4R1-R67) [[2]](diffhunk://#diff-47fb62375891d107777b8b3bd815b2cce86bd3 …
=> Add employee feedback feature and update dependencies

src/salaryReport.tsx
clientName filter was added into SalaryReport, but is not working yet, need to add filter's funtion for client name into BE
=> Unify filters between MarginReport and SalaryReport

src/components/forms/PaymentSection.tsx
dropdown added to payment platform field
=> Update payment platform to a dropdown

CLAUDE.md, src/components/forms/CreateForm.tsx, src/components/forms/EditForm.tsx, src/employeeProfiles.tsx, src/reimbursementCategories.tsx, src/reimbursements.tsx, src/resources.ts
This pull request introduces a new "Reimbursements" feature to the application, including both employee reimbursements and reimbursement categories. It adds new resource modules, integrates them into the employee profile, updates redirect logic, and provides documentation for developers. Below are the most important changes grouped by theme:
**New Features: Reimbursements & Categories**
- Added new resource modules: `reimbursements` and `reimbursement-categories`, each with list, create, and edit components (`src/reimbursements.tsx`, `src/reimbursementCategories.tsx`). [[1]](diffhunk://#diff-0f1f7f76f3fd3ee00aaaf2950ee2eb0013002aae3a8f8a989ab57244af5bce6dR1-R86) [[2]](diffhunk://#diff-76b25d78c216c964108af302a9f4841a760a00afeacdf4b80ec5371113b51f36R1-R40)
- Integrated both resources into …
=> Add reimbursement management features and documentation
