entropy-code/entropay-admin-ui

src/components/forms/CreateForm.jsx
src/components/forms/EditForm.jsx

During a create or edit contract, the field end date cant be previous to start date.
https://entropyteam.atlassian.net/browse/EN-42
if end date is previous to start date, an error message is displayed and the field is remarked with the message "End Date can't be previous to Start Date".

EN-42: validation on End Date in contracts forms

---

src/components/forms/MultiSelectInput.jsx

Employee form now allows the empty technology and profile field
https://entropyteam.atlassian.net/browse/EN-65
Employee form with empty technologies and profile
Request
New employee created

EN-65: technologies and profile bug fix

---

src/assignments.js
src/components/RedirectButton.jsx
src/components/forms/FormSections.jsx
src/components/forms/ReferenceInputItem.jsx
src/contracts.js
src/employees.js

when redirected from employee profile to contract and assignment, the employee is pre filled and not editable
https://entropyteam.atlassian.net/browse/EN-39
Manual testing
employee profile
contract form
same to assignment form

EN-39: Contract/Assignment form open from Employee must have Employee and Company pre filled and should not be editable

---

src/components/forms/CreateForm.jsx
src/components/forms/EditForm.jsx

The contract status now is based on due date. A end date can't be previous or equals to start date.
https://entropyteam.atlassian.net/browse/EN-72
Manual testing

EN-72: Contract status based on Due date

---

src/components/RedirectButton.jsx
src/employeeProfiles.js

When a new contract/employee is created from employees profile, the latest active information is prefill in the form.
https://entropyteam.atlassian.net/browse/EN-76
Manual testing
New contract prefill with information from active contract
New contract prefill from employee without active contract
New assignment prefill with information from latest employee assignment
New assignment from employee without assignment

EN-76: Prefill new contract/assignment with active information

---

src/leaveTypes.js
src/resources.js

New leave type forms to list, create, edit and delete in settings. Only admin role can access
https://entropyteam.atlassian.net/browse/EN-77
Leave Type list:
Leave Type create: 
Leave Type edit:

EN-77: Add leave type entity

---

src/employeeProfiles.js

Re order fields in Employee profile according to the criteria used in create employee from, in addition the styles where updated to hide the checkboxes in payment information data and also for all field keep the same height 
https://entropyteam.atlassian.net/browse/EN-75

[EN-75] Re order fields in Employee profile

---

src/holidays.tsx
src/types/year.ts

The logic of Year Options was changed so that it brings the years from the API
https://entropyteam.atlassian.net/browse/EN-102
Here you can see how the years bring them and the filtering also works

EN-102: Tech debt on holidays component

---

src/employeeProfiles.js

Now the front-end can receive endDate and startDate. It displays a corresponding message for the 3 cases: if only startDate is present, it shows the date and a message indicating that there are no contracts with an end date. If there is no startDate, it displays a message stating that there are no contracts. And if both dates are available, it shows both of them.
https://entropyteam.atlassian.net/browse/EN-96
If no contracts are available, it displays the following message
If there is a contract without an end date, it displays the following message:
If the contract has both start and end dates, it displays the following message:

EN-96: personal info updates

---

src/employees.js

Now we can easily see the next time off for employees, it was added to the cards.
https://entropyteam.atlassian.net/browse/EN-81
Employee cards
Employee list

EN-81: See next time off of my employees

---

src/assignments.tsx

The 'End Reason' field was added to the form, and 'Seniority' was also moved above 'Role'.
https://entropyteam.atlassian.net/browse/EN-97

EN-97: Assignments updates

---

src/components/forms/PaymentSection.jsx
src/employeeProfiles.js

adding routing number field to employee profile and payments section when an employee is created
https://entropyteam.atlassian.net/browse/EN-54
A new employee with a routing number was created. then checked that the routing number was shown correctly  
[
](url)

EN-54- Routing number field added

---

src/ptos.tsx

Changed label from "take half day off" to "half day off" when creating a half day pto
https://entropyteam.atlassian.net/browse/EN-118

EN-118: Changed label when creating a half day pto

---

src/assignments.tsx
src/clients.js
src/components/forms/EditForm.jsx
src/components/forms/FormViewSections.tsx
src/components/forms/ViewForm.jsx
src/components/layout/CustomActions.js
src/contracts.tsx
src/employeeProfiles.js
src/employees.js
src/ptos.tsx

Added a button to back out of an employees profile into the employees list.
Added a button to back out of every entity that has a "/show" page into the list of that entity. eg: assignments, contracts
Now when clicking on an employee in the contracts list, the user will be redirected to the "/show" page for that employee insted of the "/edit" one, and it works the same for every entity that has a "/show" page defined, if there's no such page defined the text won't be hyperlinked meaning it wont redirect anywhere.
https://entropyteam.atlassian.net/browse/EN-134

EN-134: Improve navigation and other minor improvements

---

src/holidays.tsx

Removed if, now holiday page defaults to a page prompting to create a new holiday instead of not loading
https://entropyteam.atlassian.net/browse/EN-160

EN-160: removed if

---

src/utils/exporter.js

When exporting a report (any), the extension should be CSV instead XLS
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7355711138
Download any report, new file is very similar but with the right extension: .csv
[employees_2024-05-08.csv](https://github.com/entropy-code/entropay-admin-ui/files/15261546/employees_2024-05-08.csv)

Adding File Extension and correct header to file

---

src/components/forms/FormSections.jsx
src/ptos.tsx

Change to make the field "Half day off" false by default:

Set the default value of the Boolean field to false

---

environments/default.env
src/App.js

We found that all queries were fetching every time the window regained focus, which is unnecessary for now; we can avoid this by passing a queryClient.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7627394904
This was tested locally by using different queries and mutations.

Use custom query client to avoid refetching on windows focus

---

src/employeeProfiles.js

In this PR we fixed the bug with the payment settlement of the last active contract that disappeared after we create a new contract.
This bug was occasioned cause the logic that we used in the front-end. Before, when we create a new contract, we took all the information of the current active contract, included the payment settlement information.
Payment settlement it's an entity on his own, so when we took the information of the payment settlement of the current active contract, we were editing the payment settlement of that active contract and  referenced it to the new contract that we were creating. That ocassionated the problem that, after we saved the new contract, the payment settlement information of the last active contract, dissapeared.
In this new implementation we changed the …

Fix for payment settlement bug after create a new contract

---

src/components/forms/EditForm.tsx
src/components/forms/FormSections.tsx

These changes fix the issues with the ptos being saved with the wrong dates and the redirection feature not working as expected.
https://3.basecamp.com/5776473/buckets/37034902/card_tables/cards/7783328878
Tested locally

Fix bug when creating ptos

---

src/billingReport.tsx

This pull request includes changes to the `src/billingReport.tsx` file to enhance the default date filtering for the billing report. The most important changes include adding default start and end dates for the previous month and updating the billing report list component to use these default dates.
Enhancements to default date filtering:
* [`src/billingReport.tsx`](diffhunk://#diff-002612cfcbcc51a94def2918bf354c16eee0cede3096b3caded8c88372b57775R49-R52): Added `defaultStartDate` and `defaultEndDate` constants to calculate the first and last days of the previous month using the `moment` library.
* [`src/billingReport.tsx`](diffhunk://#diff-002612cfcbcc51a94def2918bf354c16eee0cede3096b3caded8c88372b57775L73-R84): Updated the `BillingReportList` component to use the new default date values …

Set default date range to previous month in billing report

---

src/billingReport.tsx
src/projects.tsx

This pull request includes changes to two files, `src/billingReport.tsx` and `src/projects.tsx`, to add new fields and sorting functionality. The most important changes include adding a "notes" field to the billing report, adding a "Paid PTO" field to the projects list, and enabling sorting by "internalId" in the billing report.
Changes to `src/billingReport.tsx`:
* Added "Notes" to the `headersRename` and `headers` arrays. [[1]](diffhunk://#diff-002612cfcbcc51a94def2918bf354c16eee0cede3096b3caded8c88372b57775R27) [[2]](diffhunk://#diff-002612cfcbcc51a94def2918bf354c16eee0cede3096b3caded8c88372b57775R40)
* Enabled sorting by "internalId" in ascending order in the `BillingReportList` component.
* Added a `TextField` for the "notes" field in the `BillingReportList` component.
Changes to …

Add "Paid PTO" and "Notes" fields to projects and billing

---

src/marginReport.tsx
src/resources.ts

Introduced a new Margin Report feature by adding `MarginReportList` to the resources. The report includes a list view with filters for date range, data export functionality, and relevant fields like rates, hours, and margin. Updated `resources.ts` to include the new endpoint for the margin reports.

Add Margin Report to available resources

---

src/resources.ts
src/turnoverReport.tsx

Implemented a new `TurnoverReportList` component featuring filters for start date, end date, level, and period. Added default filter values for the previous month. Integrated export functionality with customizable headers. Registered the new report list in `resources.ts`.

Add turnover report list with filters and export functionality

---

src/components/forms/FormSections.tsx
src/components/forms/ReferenceAutocompleteItem.tsx
src/contracts.tsx

This pull request introduces a new autocomplete input component for reference data in forms, replacing the previous select input for the "profile" field and updating the form rendering logic to support this new input type.
**Form Input Improvements:**
* Added a new `ReferenceAutocompleteItem` component that uses `react-admin`'s `AutocompleteInput` to fetch and display reference choices dynamically. This component handles fetching data, error handling, and rendering the input. (`src/components/forms/ReferenceAutocompleteItem.tsx`)
* Updated the form rendering logic in `FormSections.tsx` to support the new "AutocompleteInput" type, rendering the `ReferenceAutocompleteItem` when specified in the form configuration. [[1]](diffhunk://#diff-904f684e3f4ff5b158e91a87f4198d0380df8f1c9a2343ca49018f8 …

Add ReferenceAutocompleteItem component and integrate
